/**
 * Mock data for medical reports
 */

import { MedicalReport, ReportStatus, ReportType } from '../types';

// Generate a random ID
const generateId = () => Math.random().toString(36).substring(2, 15);

// Generate a random date within the last year
const randomDate = (startDate?: Date) => {
  const start = startDate || new Date(Date.now() - 365 * 24 * 60 * 60 * 1000);
  const end = new Date();
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

// Mock medical reports data
export const MOCK_REPORTS: MedicalReport[] = [
  // New blood reports
  {
    id: 'rep_' + generateId(),
    userId: 'user1',
    type: 'CBC',
    title: 'Complete Blood Count with Differential',
    description: 'Comprehensive blood analysis with white cell differential',
    status: 'completed',
    fileUrl: '/reports/cbc_differential.pdf',
    fileName: 'cbc_differential.pdf',
    fileType: 'application/pdf',
    fileSize: 1024 * 1024 * 2.1, // 2.1 MB
    uploadDate: randomDate(),
    processedDate: randomDate(),
    provider: 'Apollo Diagnostics',
    patientName: 'Sarah Johnson',
    patientDOB: '1985-06-15',
    reportDate: '2023-11-10',
    results: [
      {
        name: 'WBC',
        value: 11.5,
        unit: 'K/uL',
        referenceRange: { min: 4.5, max: 11.0 },
        status: 'high',
      },
      {
        name: 'RBC',
        value: 4.8,
        unit: 'M/uL',
        referenceRange: { min: 4.5, max: 5.9 },
        status: 'normal',
      },
      {
        name: 'Hemoglobin',
        value: 13.8,
        unit: 'g/dL',
        referenceRange: { min: 13.5, max: 17.5 },
        status: 'normal',
      },
      {
        name: 'Hematocrit',
        value: 41.5,
        unit: '%',
        referenceRange: { min: 41.0, max: 53.0 },
        status: 'normal',
      },
      {
        name: 'Platelets',
        value: 320,
        unit: 'K/uL',
        referenceRange: { min: 150, max: 450 },
        status: 'normal',
      },
      {
        name: 'Neutrophils',
        value: 75,
        unit: '%',
        referenceRange: { min: 40, max: 70 },
        status: 'high',
      },
      {
        name: 'Lymphocytes',
        value: 18,
        unit: '%',
        referenceRange: { min: 20, max: 40 },
        status: 'low',
      },
      {
        name: 'Monocytes',
        value: 5,
        unit: '%',
        referenceRange: { min: 2, max: 10 },
        status: 'normal',
      },
      {
        name: 'Eosinophils',
        value: 1.5,
        unit: '%',
        referenceRange: { min: 1, max: 6 },
        status: 'normal',
      },
      {
        name: 'Basophils',
        value: 0.5,
        unit: '%',
        referenceRange: { min: 0, max: 2 },
        status: 'normal',
      },
    ],
    analysis: {
      summary: 'Elevated white blood cell count with neutrophilia and relative lymphopenia, suggesting possible acute infection or inflammation.',
      findings: [
        'Elevated white blood cell count (leukocytosis)',
        'Increased neutrophil percentage (neutrophilia)',
        'Decreased lymphocyte percentage (relative lymphopenia)',
        'Normal red blood cell parameters',
        'Normal platelet count'
      ],
      recommendations: [
        'Follow up with healthcare provider to evaluate for possible infection or inflammatory condition',
        'Consider additional testing such as CRP or ESR to assess inflammation',
        'Repeat CBC in 1-2 weeks to monitor response',
        'Stay well-hydrated and monitor for fever or other symptoms'
      ],
      possibleConditions: [
        {
          name: 'Bacterial Infection',
          probability: 0.75,
          description: 'Elevated neutrophils often indicate bacterial infection',
        },
        {
          name: 'Inflammatory Condition',
          probability: 0.60,
          description: 'Leukocytosis can be associated with various inflammatory conditions',
        },
        {
          name: 'Physiologic Stress Response',
          probability: 0.45,
          description: 'Physical or emotional stress can cause temporary elevation in white blood cells',
        },
      ],
      followUpRecommended: true,
      followUpTimeframe: '1 week',
      aiConfidenceScore: 0.88,
    },
    createdAt: randomDate(),
    updatedAt: randomDate(),
  },
  {
    id: 'rep_' + generateId(),
    userId: 'user1',
    type: 'Metabolic Panel',
    title: 'Comprehensive Metabolic Panel',
    description: 'Blood chemistry and kidney/liver function tests',
    status: 'completed',
    fileUrl: '/reports/metabolic_panel_comprehensive.pdf',
    fileName: 'metabolic_panel_comprehensive.pdf',
    fileType: 'application/pdf',
    fileSize: 1024 * 1024 * 1.8, // 1.8 MB
    uploadDate: randomDate(),
    processedDate: randomDate(),
    provider: 'MedLife Diagnostics',
    patientName: 'Michael Chen',
    patientDOB: '1978-09-22',
    reportDate: '2023-12-05',
    results: [
      {
        name: 'Glucose',
        value: 105,
        unit: 'mg/dL',
        referenceRange: { min: 70, max: 99 },
        status: 'high',
      },
      {
        name: 'BUN (Blood Urea Nitrogen)',
        value: 18,
        unit: 'mg/dL',
        referenceRange: { min: 7, max: 20 },
        status: 'normal',
      },
      {
        name: 'Creatinine',
        value: 0.9,
        unit: 'mg/dL',
        referenceRange: { min: 0.6, max: 1.2 },
        status: 'normal',
      },
      {
        name: 'eGFR',
        value: 98,
        unit: 'mL/min/1.73m²',
        referenceRange: { min: 90, max: 120 },
        status: 'normal',
      },
      {
        name: 'Sodium',
        value: 141,
        unit: 'mmol/L',
        referenceRange: { min: 136, max: 145 },
        status: 'normal',
      },
      {
        name: 'Potassium',
        value: 4.2,
        unit: 'mmol/L',
        referenceRange: { min: 3.5, max: 5.1 },
        status: 'normal',
      },
      {
        name: 'Chloride',
        value: 102,
        unit: 'mmol/L',
        referenceRange: { min: 98, max: 107 },
        status: 'normal',
      },
      {
        name: 'Carbon Dioxide',
        value: 24,
        unit: 'mmol/L',
        referenceRange: { min: 22, max: 29 },
        status: 'normal',
      },
      {
        name: 'Calcium',
        value: 9.5,
        unit: 'mg/dL',
        referenceRange: { min: 8.6, max: 10.2 },
        status: 'normal',
      },
      {
        name: 'Protein, Total',
        value: 7.2,
        unit: 'g/dL',
        referenceRange: { min: 6.4, max: 8.2 },
        status: 'normal',
      },
      {
        name: 'Albumin',
        value: 4.3,
        unit: 'g/dL',
        referenceRange: { min: 3.5, max: 5.0 },
        status: 'normal',
      },
      {
        name: 'Globulin',
        value: 2.9,
        unit: 'g/dL',
        referenceRange: { min: 2.3, max: 3.5 },
        status: 'normal',
      },
      {
        name: 'Albumin/Globulin Ratio',
        value: 1.5,
        unit: '',
        referenceRange: { min: 1.2, max: 2.2 },
        status: 'normal',
      },
      {
        name: 'Bilirubin, Total',
        value: 0.8,
        unit: 'mg/dL',
        referenceRange: { min: 0.1, max: 1.2 },
        status: 'normal',
      },
      {
        name: 'Alkaline Phosphatase',
        value: 75,
        unit: 'U/L',
        referenceRange: { min: 40, max: 129 },
        status: 'normal',
      },
      {
        name: 'AST',
        value: 32,
        unit: 'U/L',
        referenceRange: { min: 0, max: 40 },
        status: 'normal',
      },
      {
        name: 'ALT',
        value: 45,
        unit: 'U/L',
        referenceRange: { min: 0, max: 41 },
        status: 'high',
      },
    ],
    analysis: {
      summary: 'Mildly elevated glucose and ALT levels with otherwise normal metabolic parameters.',
      findings: [
        'Elevated fasting glucose (prediabetic range)',
        'Mildly elevated ALT (liver enzyme)',
        'Normal kidney function',
        'Normal electrolyte levels',
        'Normal protein levels'
      ],
      recommendations: [
        'Follow up with healthcare provider to discuss elevated glucose and ALT',
        'Consider lifestyle modifications including diet and exercise',
        'Monitor blood glucose levels regularly',
        'Limit alcohol consumption to protect liver health',
        'Repeat metabolic panel in 3-6 months'
      ],
      possibleConditions: [
        {
          name: 'Prediabetes',
          probability: 0.70,
          description: 'Elevated blood glucose that is not yet in the diabetic range',
        },
        {
          name: 'Non-alcoholic Fatty Liver Disease',
          probability: 0.65,
          description: 'Fat accumulation in the liver that can cause elevated liver enzymes',
        },
        {
          name: 'Metabolic Syndrome',
          probability: 0.50,
          description: 'Cluster of conditions including high blood sugar and abnormal cholesterol levels',
        },
      ],
      followUpRecommended: true,
      followUpTimeframe: '3 months',
      aiConfidenceScore: 0.90,
    },
    createdAt: randomDate(),
    updatedAt: randomDate(),
  },
  {
    id: 'rep_' + generateId(),
    userId: 'user1',
    type: 'Other',
    title: 'Thyroid Function Panel',
    description: 'Comprehensive thyroid hormone assessment',
    status: 'completed',
    fileUrl: '/reports/thyroid_panel.pdf',
    fileName: 'thyroid_panel.pdf',
    fileType: 'application/pdf',
    fileSize: 1024 * 1024 * 1.5, // 1.5 MB
    uploadDate: randomDate(),
    processedDate: randomDate(),
    provider: 'Thyrocare Diagnostics',
    patientName: 'Emily Rodriguez',
    patientDOB: '1990-03-12',
    reportDate: '2023-10-28',
    results: [
      {
        name: 'TSH (Thyroid Stimulating Hormone)',
        value: 6.8,
        unit: 'mIU/L',
        referenceRange: { min: 0.4, max: 4.0 },
        status: 'high',
      },
      {
        name: 'Free T4',
        value: 0.8,
        unit: 'ng/dL',
        referenceRange: { min: 0.8, max: 1.8 },
        status: 'normal',
        notes: 'Lower end of normal range'
      },
      {
        name: 'Free T3',
        value: 2.9,
        unit: 'pg/mL',
        referenceRange: { min: 2.3, max: 4.2 },
        status: 'normal',
      },
      {
        name: 'Thyroid Peroxidase Antibodies (TPO)',
        value: 95,
        unit: 'IU/mL',
        referenceRange: { min: 0, max: 34 },
        status: 'high',
      },
      {
        name: 'Thyroglobulin Antibodies',
        value: 42,
        unit: 'IU/mL',
        referenceRange: { min: 0, max: 40 },
        status: 'high',
      },
    ],
    analysis: {
      summary: 'Elevated TSH with positive thyroid antibodies suggesting subclinical hypothyroidism with autoimmune etiology (Hashimotos thyroiditis).',
      findings: [
        'Elevated TSH level',
        'Free T4 at lower end of normal range',
        'Normal Free T3 level',
        'Elevated thyroid peroxidase antibodies (TPO)',
        'Slightly elevated thyroglobulin antibodies'
      ],
      recommendations: [
        'Follow up with an endocrinologist to evaluate for hypothyroidism',
        'Consider thyroid hormone replacement therapy',
        'Monitor thyroid function every 3-6 months',
        'Evaluate for other autoimmune conditions',
        'Consider dietary modifications (adequate iodine, selenium)'
      ],
      possibleConditions: [
        {
          name: 'Subclinical Hypothyroidism',
          probability: 0.85,
          description: 'Elevated TSH with normal thyroid hormone levels, may progress to overt hypothyroidism',
        },
        {
          name: 'Hashimoto\'s Thyroiditis',
          probability: 0.80,
          description: 'Autoimmune condition where the immune system attacks the thyroid gland',
        },
        {
          name: 'Autoimmune Thyroiditis',
          probability: 0.75,
          description: 'Inflammation of the thyroid gland caused by autoimmune factors',
        },
      ],
      followUpRecommended: true,
      followUpTimeframe: '1 month',
      aiConfidenceScore: 0.92,
    },
    createdAt: randomDate(),
    updatedAt: randomDate(),
  },
  {
    id: 'rep_' + generateId(),
    userId: 'user1',
    type: 'CBC',
    title: 'Complete Blood Count',
    description: 'Routine annual CBC test',
    status: 'completed',
    fileUrl: '/reports/cbc_report.pdf',
    fileName: 'cbc_report.pdf',
    fileType: 'application/pdf',
    fileSize: 1024 * 1024 * 2.3, // 2.3 MB
    uploadDate: randomDate(),
    processedDate: randomDate(),
    provider: 'LabCorp Medical',
    patientName: 'John Smith',
    results: [
      {
        name: 'WBC',
        value: 7.2,
        unit: 'K/uL',
        referenceRange: { min: 4.5, max: 11.0 },
        status: 'normal',
      },
      {
        name: 'RBC',
        value: 5.1,
        unit: 'M/uL',
        referenceRange: { min: 4.5, max: 5.9 },
        status: 'normal',
      },
      {
        name: 'Hemoglobin',
        value: 14.2,
        unit: 'g/dL',
        referenceRange: { min: 13.5, max: 17.5 },
        status: 'normal',
      },
      {
        name: 'Hematocrit',
        value: 42.1,
        unit: '%',
        referenceRange: { min: 41.0, max: 53.0 },
        status: 'normal',
      },
      {
        name: 'Platelets',
        value: 290,
        unit: 'K/uL',
        referenceRange: { min: 150, max: 450 },
        status: 'normal',
      },
    ],
    analysis: {
      summary: 'All blood count parameters are within normal ranges.',
      findings: ['Normal white blood cell count', 'Normal red blood cell count', 'Normal platelet count'],
      recommendations: ['Continue with regular health maintenance', 'Repeat CBC in one year'],
      aiConfidenceScore: 0.95,
    },
    createdAt: randomDate(),
    updatedAt: randomDate(),
  },
  {
    id: 'rep_' + generateId(),
    userId: 'user1',
    type: "Lipid Panel",
    title: 'Lipid Profile',
    description: 'Cholesterol and triglycerides screening',
    status: 'completed',
    fileUrl: '/reports/lipid_panel.pdf',
    fileName: 'lipid_panel.pdf',
    fileType: 'application/pdf',
    fileSize: 1024 * 1024 * 1.7, // 1.7 MB
    uploadDate: randomDate(),
    processedDate: randomDate(),
    provider: 'Quest Diagnostics',
    patientName: 'John Smith',
    results: [
      {
        name: 'Total Cholesterol',
        value: 210,
        unit: 'mg/dL',
        referenceRange: { min: 0, max: 200 },
        status: 'high',
      },
      {
        name: 'HDL Cholesterol',
        value: 45,
        unit: 'mg/dL',
        referenceRange: { min: 40, max: 60 },
        status: 'normal',
      },
      {
        name: 'LDL Cholesterol',
        value: 130,
        unit: 'mg/dL',
        referenceRange: { min: 0, max: 100 },
        status: 'high',
      },
      {
        name: 'Triglycerides',
        value: 175,
        unit: 'mg/dL',
        referenceRange: { min: 0, max: 150 },
        status: 'high',
      },
    ],
    analysis: {
      summary: 'Elevated lipid levels indicating moderate hyperlipidemia.',
      findings: [
        'Total cholesterol is above the recommended range',
        'LDL ("bad") cholesterol is elevated',
        'Triglycerides are elevated',
      ],
      recommendations: [
        'Consider dietary modifications to reduce saturated fat intake',
        'Increase physical activity to at least 150 minutes per week',
        'Follow up with healthcare provider to discuss treatment options',
        'Repeat lipid panel in 3 months',
      ],
      possibleConditions: [
        {
          name: 'Hyperlipidemia',
          probability: 0.85,
          description: 'Elevated levels of lipids (fats) in the blood',
        },
      ],
      followUpRecommended: true,
      followUpTimeframe: '3 months',
      aiConfidenceScore: 0.92,
    },
    createdAt: randomDate(),
    updatedAt: randomDate(),
  },
  {
    id: 'rep_' + generateId(),
    userId: 'user1',
    type: "ECG",
    title: 'Electrocardiogram',
    description: 'Routine ECG for heart health screening',
    status: 'completed',
    fileUrl: '/reports/ecg_report.pdf',
    fileName: 'ecg_report.pdf',
    fileType: 'application/pdf',
    fileSize: 1024 * 1024 * 3.1, // 3.1 MB
    uploadDate: randomDate(),
    processedDate: randomDate(),
    provider: 'City Heart Clinic',
    patientName: 'John Smith',
    results: [
      {
        name: 'Heart Rate',
        value: 72,
        unit: 'bpm',
        referenceRange: { min: 60, max: 100 },
        status: 'normal',
      },
      {
        name: 'PR Interval',
        value: 160,
        unit: 'ms',
        referenceRange: { min: 120, max: 200 },
        status: 'normal',
      },
      {
        name: 'QRS Duration',
        value: 90,
        unit: 'ms',
        referenceRange: { min: 80, max: 120 },
        status: 'normal',
      },
      {
        name: 'QT Interval',
        value: 380,
        unit: 'ms',
        referenceRange: { min: 350, max: 450 },
        status: 'normal',
      },
    ],
    analysis: {
      summary: 'Normal sinus rhythm with no significant abnormalities.',
      findings: ['Normal heart rate', 'Normal cardiac intervals', 'No arrhythmias detected'],
      recommendations: ['Continue regular cardiac check-ups as recommended by your physician'],
      aiConfidenceScore: 0.97,
    },
    createdAt: randomDate(),
    updatedAt: randomDate(),
  },
  {
    id: 'rep_' + generateId(),
    userId: 'user1',
    type: 'X-Ray',
    title: 'Chest X-Ray',
    description: 'Routine chest X-ray for annual physical',
    status: 'pending',
    fileUrl: '/reports/chest_xray.pdf',
    fileName: 'chest_xray.pdf',
    fileType: 'application/pdf',
    fileSize: 1024 * 1024 * 5.2, // 5.2 MB
    uploadDate: randomDate(),
    provider: 'Metro Radiology',
    patientName: 'John Smith',
    createdAt: randomDate(),
    updatedAt: randomDate(),
  },
  {
    id: 'rep_' + generateId(),
    userId: 'user1',
    type: 'Metabolic Panel',
    title: 'Comprehensive Metabolic Panel',
    description: 'Blood chemistry and kidney function tests',
    status: 'processing',
    fileUrl: '/reports/metabolic_panel.pdf',
    fileName: 'metabolic_panel.pdf',
    fileType: 'application/pdf',
    fileSize: 1024 * 1024 * 1.9, // 1.9 MB
    uploadDate: randomDate(),
    provider: 'LabCorp Medical',
    patientName: 'John Smith',
    createdAt: randomDate(),
    updatedAt: randomDate(),
  },
];